In [8]:
import torch
a = torch.tensor([[[1,2,3],[4,5,6]],[[2,4,6],[3,6,9]]])
print(a)
b = a.view((-1, 6))
print(b)
c = b.view((-1, 3, 2))
print(c)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[2, 4, 6],
         [3, 6, 9]]])
tensor([[1, 2, 3, 4, 5, 6],
        [2, 4, 6, 3, 6, 9]])
tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[2, 4],
         [6, 3],
         [6, 9]]])


In [12]:
from bert_serving.client import BertClient
bc = BertClient(ip='10.15.82.239',port=8190, check_version=False, check_length=False)
a = bc.encode(['你好我是怒呼出的口号'])
print(a.shape)

(1, 200, 768)


In [21]:
import torch
a=torch.Tensor([[[1,2],[2,3]],[[4,5],[6,7]]])
print(a)
b = a.permute(2, 1, 0)


tensor([[[1., 2.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])


In [28]:
def fun(u, **kargs):
    print(kargs['a'])
fun(1,a=3,b=34,c=5)

3
